### PR TITLE
Update README.md to include events that are raised

### PR DESCRIPTION
**Pull request by tracker1**
Add Events section to show which events may be raised.

### CODE REVIEW

**Comment by tracker1** [comment]
I was seeing issues in production and had to dig into the source to determine the events that are/were in use.

**Comment by tracker1** [comment]
It's still valid...

**Comment by tracker1** [comment]
@sameerkhanna @felipeska @sahirmemon @fceldeiro @jugaltheshah @aacebo @timcosta

This PR has been sitting a long while now...

**Comment by jugaltheshah** [comment]
> @sameerkhanna @felipeska @sahirmemon @fceldeiro @jugaltheshah @aacebo @timcosta
> 
> This PR has been sitting a long while now...

Thank you for the PR @tracker1 and apologies for the delay. Seems like it's now out of date with `master` would you be able to rebase? I'll then review and merge it today if everything's in order.

**Pull request closed without merging**
