### PR TITLE
feat: mocha 6, implement lint stye, run lint in ci

### PR DESCRIPTION
**Pull request by ryanhallcs**
This change is massive but no functional changes were made. All same 30 tests still run and pass the summary of changes follows:

- Implement lint and run in CI - this is 99% of this PR (indentation, following hapi style guidelines, arrow functions, etc)
- Upgrading to mocha 6
- removing `mocha.opts` in lieu of package.json config as suggested by mocha
- Upgrading supported node version to `>= 10.x`
- Bump circle ci node image pin to latest sha

### CODE REVIEW

**Comment by cilindrox** [comment]
Thanks @ryanhallcs been meaning to tackle this since forever

**Comment by cilindrox** [comment]
Seems builds are timing out - perhaps it's missing a `done()` call on the suite?

**Comment by ryanhallcs** [comment]
strange i can't replicate that with `npm test` or docker-compose, looking into it still

**Comment by ryanhallcs** [comment]
turns out mocha <4 auto-exitted (this PR moves from 3 -> 6) - and from 4 or mocha enforced devs to ensure tests were cleaned up. since the existing tests were leaving _something_ open (socket, connection) - they never exit under certain circumstances.

i tried adding `.close()` calls but can replicate and confirm it is not enough when exchanges are created. something is left open, but since it has always been this case I will leave that for another PR

**Pull request merged**
