### PR TITLE
fix: don't error on message parse error

### PR DESCRIPTION
**Pull request by DiegoRBaquero**
BREAKING CHANGE

### CODE REVIEW

**Review by timcosta — APPROVED** [review]
Breaking change, but i like it.

**Comment by jvelezpo** [comment]
I would like this PR to sit here until next week and see what input @ryanhallcs has about it

Also i think @duvanmo make his point [here](https://pagerinc.slack.com/archives/C2U5ECFHD/p1602087837197500) as well and I know he does not like this change

**Comment by ryanhallcs** [comment]
i don't understand this change. errors can be handled upstream, why would we not emit an error when one occurs?

**Comment by DiegoRBaquero** [comment]
> i don't understand this change. errors can be handled upstream, why would we not emit an error when one occurs?

The way that they are being handled is restarting, our services assume jackrabbit error is a disconnect and call `process.exit(1)`

**Comment by ryanhallcs** [comment]
i think we then need to revisit our service error handling instead of suppressing errors

**Review by cilindrox — COMMENTED** [review]
Agreed on the comments above - IMO apps should handle the errors or ignoring them - don't think that's a responsibility for jackrabbit.
We could look into subclassing errors or adding properties so it's easier to `catch` and handle them from the apps.

**Pull request closed without merging**
